### ISSUE TITLE
Documented feature does not exist; exclude with lambdas

### ISSUE THREAD

**Issue by wgwz** [arlyon/aiobreaker#12] opened 2021-05-04 23:51 UTC
ignoring exceptions based on the result of lambda functions is documented but not supported it seems. when trying to use the pattern documented here:

https://aiobreaker.netlify.app/usage.html#ignoring-specific-exceptions

i see this:

```
TypeError: issubclass() arg 2 must be a class or tuple of classes
```

would you be willing to accept and review a PR for this?

**Comment by arlyon** [comment] 2021-05-05 12:46
Hi, yes, abosolutely. Seems that this feature is not working as intended. Much of the code is still the same after forking pybreaker, however it seems clear from that block that the intention is that lambdas should trigger the elif block:

https://github.com/arlyon/aiobreaker/blob/master/aiobreaker/circuitbreaker.py#L188-L193

Happy to review (and merge) any PRs you have!

**Comment by wgwz** [comment] 2021-05-06 00:25
ah, ok! looks we just need a release. the latest version in pypi is 1.1.0 and i don't think the code you shared exists in that release:

https://github.com/arlyon/aiobreaker/blob/1.1.0/aiobreaker/circuitbreaker.py#L179-L189

**Comment by wgwz** [comment] 2021-05-06 00:29
indeed, indeed! here's the commit: https://github.com/arlyon/aiobreaker/commit/a878de62090312917b2603555243af189daf2f6a

**Comment by wgwz** [comment] 2021-05-16 21:16
Hey @arlyon, just wondering if you could make a release for this, thanks!

**Comment by arlyon** [comment] 2021-05-17 11:55
Uploading now. Thanks for the interest in this project. Going to close the issue :)

**Closed** 2021-05-17 11:55 UTC

**Comment by wgwz** [comment] 2021-05-24 20:33
@arlyon thank you for maintaining the project! i appreciate the upload
